services:
  postgres:
    image: postgres:16
    container_name: proteinos-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: proteinos
      POSTGRES_USER: proteinadmin
      POSTGRES_PASSWORD: password123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: proteinos-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@proteinos.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "5050:80"

    depends_on:
      - postgres

volumes:
  postgres_data:
